apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool-syslog-reader
spec:
  selector:
    matchLabels:
      app: multitool-syslog-reader
  template:
    metadata:
      labels:
        app: multitool-syslog-reader
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        command: ["/bin/sh", "-c", "tail -f /var/log/syslog"]
        volumeMounts:
        - name: syslog
          mountPath: /var/log
      volumes:
      - name: syslog
        hostPath:
          path: /var/log
          type: Directory
